### PR TITLE
Use latest version of MARBL

### PR DESCRIPTION
**Pull request by mnlevy1981**
### Description of changes:

A new version of MARBL has been released to support autotrophs that are explicit calcifiers

### Testing:
 
Test case/suite: I ran `aux_pop` on cheyenne and `aux_pop_MARBL` on both cheyenne and hobart
Test status: existing tests are all bit-for-bit; I added a new test to exercise the new MARBL code, and also `marbl_in` has changed so `NLCOMP` tests fail if the ecosystem is enabled

User interface (namelist or namelist defaults) changes? Yes, for compsets using MARBL (see above)

### CODE REVIEW

**Comment by mnlevy1981** [comment]
Note: I still need to update `namelist_defaults_pop.xml` to point to a new `init_ecosys_init_file` when running with `OCN_BGC_CONFIG=cesm2.1+cocco`; I will generate that file, run the test suite one more time, and then comment that this is ready to be merged.

**Comment by mnlevy1981** [comment]
Testing is complete -- as expected, `aux_pop` generated `NLCOMP` failures for all tests that used MARBL-enabled compsets but all `BASELINE` tests passed. New initial condition file has been added to inputdata and (and has already been downloaded on hobart).

I'm unclear about the git-based process for merging and tagging: should I update `ChangeLog`? Are we still tagging every commit? It looks like master is a little ahead of the last tag because @alperaltuntas updated github templates, but this is the first PR since the last tag that changes source code.

**Comment by alperaltuntas** [comment]
> Are we still tagging every commit?

My feeling is that we shouldn't necessarily tag every commit but should tag every PR to be merged. Perhaps we may delay tag creation if a PR is not so extensive and doesn't require us to run aux_pop, unless the changes need to be added to a CESM tag promptly. Not sure if such exceptions would cause impracticality. As for updating ChangeLog, I think we should update it each time creating a new tag. What do you think @mnlevy1981 @klindsay28 ?

**Comment by mnlevy1981** [comment]
I like the ChangeLog and am happy to keep it alive. I'll make one more commit to this branch / PR to add some notes about the tag.

@alperaltuntas do you want me to wait for #7 before merging this? If so, I'll hold off on the ChangeLog update until after merging in the new `master`.

**Pull request merged**
